httpProxy: "${http_proxy-}"

httpsProxy: "${https_proxy-}"

nodeLinker: node-modules


npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  datadocs:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmAuthToken: "${GITHUB_TOKEN-}"
    npmAlwaysAuth: true
injectEnvironmentFiles:
  - .env?
